### PR TITLE
Update Sportsnet's feed URL

### PR DESCRIPTION
**Pull request by yguns31**
Update Sportsnet's feed URL from https://d290qmen6zswb.cloudfront.net/ticker  to  https://mobile-statsv2.sportsnet.ca/ticker

### CODE REVIEW

**Comment by Brew-tus** [comment]
Awesome, thank you so much that worked!!!!!

**Comment by mcaminiti** [comment]
Thanks for the fix.  Verified this works and fixes the issues I had as well.

**Comment by sanj926** [comment]
worked for me as well! Thanks!

**Comment by jclarke0000** [comment]
This is now fixed in master.

**Pull request closed without merging**
